name: glados
description: 'A simple testing framework that tries to break your properties.'
version: 1.1.6

repository: https://github.com/MarcelGarus/glados

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^6.3.0
  build: ^2.0.0
  characters: ^1.1.0
  meta: ^1.3.0
  source_gen: ^1.0.0
  test: ^1.20.0

dev_dependencies:
  lints: ^3.0.0
